### ISSUE TITLE
Unable to navigate between displays with "workspaces span displays"

### ISSUE THREAD

**Issue by theroncross** [pop-os/cosmic-workspaces-epoch#97] opened 2024-10-07 15:52 UTC
# expected behavior
When the "workspaces span displays" and "workpaces orientation: vertical" settings are active, I should be able to navigate between windows on multiple displays as if they are in the same display/workspace (as is the case in the current Pop!OS tiling).

# actual behavior
I have two displays: built-in laptop on left, external monitor on right. `Super+{left,right}` moves focus between windows within a display, but not between displays.

**Note:** if the focus is on the left-most window in the right display and I press `super+left`, the focus does not change to the left display. However, it now takes two presses of `super+right` to move focus to the next window to the right. 

```
❯ apt list | grep cosmic

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

budgie-wallpapers-cosmic/jammy,jammy 22.04 all
cosmic-app-library/jammy,now 0.1.0~1728164406~22.04~8cfe24c amd64 [installed,automatic]
cosmic-applets/jammy,jammy,now 0.1.0~1727881419~22.04~652ea5b amd64 [installed,automatic]
cosmic-bg/jammy,jammy,now 0.1.0~1725661327~22.04~584f6b3 amd64 [installed,automatic]
cosmic-comp/jammy,jammy,now 0.1~1727906110~22.04~a96394f amd64 [installed,automatic]
cosmic-design-demo/jammy,jammy 0.1.0~1704748391~22.04~d58cfad amd64
cosmic-edit/jammy,now 0.1.0~1728226838~22.04~18554f3 amd64 [installed,automatic]
cosmic-files/jammy,now 0.1.0~1728135543~22.04~e997bbb amd64 [installed,automatic]
cosmic-greeter-daemon/jammy,now 0.1.0~1728256123~22.04~3b3b5ea amd64 [installed,automatic]
cosmic-greeter/jammy,now 0.1.0~1728256123~22.04~3b3b5ea amd64 [installed,automatic]
cosmic-icons/jammy,jammy,now 0.1.0~1727905915~22.04~3fdc217 amd64 [installed,automatic]
cosmic-launcher/jammy,jammy,now 0.1.0~1726585048~22.04~5c9757b amd64 [installed,automatic]
cosmic-notifications/jammy,jammy,now 0.1.0~1722531142~22.04~e9abef5 amd64 [installed,automatic]
cosmic-osd/jammy,jammy,now 0.1.0~1727370498~22.04~570f35f amd64 [installed,automatic]
cosmic-panel/jammy,jammy,now 0.1.0~1727472240~22.04~0ce85da amd64 [installed,automatic]
cosmic-player/jammy 0.1.0~1728261391~22.04~87e49a8 amd64
cosmic-randr/jammy,jammy,now 0.1.0~1722404448~22.04~71fabbb amd64 [installed,automatic]
cosmic-screenshot/jammy,jammy,now 0.1.0~1721939965~22.04~031eb66 amd64 [installed,automatic]
cosmic-session/jammy,now 0.1.0~1728079516~22.04~b3900bc amd64 [installed]
cosmic-settings-daemon/jammy,jammy,now 0.1.0~1727366100~22.04~2f17f33 amd64 [installed,automatic]
cosmic-settings/jammy,now 0.1.0~1728131303~22.04~c6d6f5e amd64 [installed,automatic]
cosmic-store/jammy,now 0.1.0~1728164443~22.04~5f3d0fd amd64 [installed,automatic]
cosmic-term/jammy,now 0.1.0~1728164510~22.04~64e95eb amd64 [installed,automatic]
cosmic-wallpapers/jammy,jammy,jammy,jammy,now 1.0.0~1727440723~22.04~8d1d23a all [installed,automatic]
cosmic-workspaces/jammy,jammy,now 0.1.0~1723068086~22.04~70d6c41 amd64 [installed,automatic]
gnome-shell-extension-cosmic-dock/jammy,jammy,jammy,jammy,now 72~ubuntu2pop0~1664903880~22.04~6700449 all [installed,automatic]
gnome-shell-extension-cosmic-workspaces/jammy,jammy,jammy,jammy,now 0.1.0~1716422595~22.04~6d90fb4 all [installed,automatic]
node-cosmiconfig/jammy,jammy 7.0.0+ds1-2 all
pop-cosmic/jammy,jammy,jammy,jammy,now 0.1.0~1706558821~22.04~608a095 all [installed,automatic]
ubuntu-mate-wallpapers-cosmic/jammy,jammy 22.04.17 all
ubuntu-wallpapers-cosmic/jammy,jammy 22.04.4-0ubuntu1 all
ubuntukylin-wallpapers-cosmic/jammy,jammy 20.10.1 all
ubuntustudio-wallpapers-cosmic/jammy,jammy 22.04.9 all
xdg-desktop-portal-cosmic/jammy,now 0.1.0pop1~1728135788~22.04~309f586 amd64 [installed,automatic]
```

```
❯ xrandr --listmonitors
Monitors: 2
 0: +eDP-1 1920/340x1080/190+0+768  eDP-1
 1: +DP-2 2560/700x1440/400+1919+0  DP-2
```

**Comment by leviport** [comment] 2024-10-14 16:25
I believe this is a duplicate of https://github.com/pop-os/cosmic-workspaces-epoch/issues/95

**Closed by leviport** 2024-10-14 16:25 UTC

**Comment by Ravengood** [comment] 2024-10-15 13:35
Same issue here except i'm using horizontal workspaces

On Pop!_OS 22.04 with COSMIC DE installed, extra monitor attached to Dell laptop, "Workspaces span Displays" activated with Workspace Orientation Horizontal.

![image](https://github.com/user-attachments/assets/fe9a9a0d-d46f-43dc-afd8-041c641655fc)

keyboard navigation is broken when i move a window to another workspace or display ... window focus is left behind on the workspace I left (probably focusing last active window) instead of following the window i'm moving to the new workspace/display (very often i need to move it further or interact with the window, but to do that i need to regain focus) ... this seems like a bug since working with "Seperate Workspaces" works the way I would expect?

Please let me know if you need further information
