### ISSUE TITLE
Window previews disappear off the edge of the screen

### ISSUE THREAD

**Issue by fizzyizzy05** [pop-os/cosmic-workspaces-epoch#82] opened 2024-08-09 16:04 UTC
When using horizontal workspaces, in workspaces with either a single maximised window or horizontally split windows, the bottom edges of the window previews are cut off so that you can't see the window titles. This doesn't seem to happen when using vertical workspaces, or when using other layouts such as grid, or vertically split windows.
![image](https://github.com/user-attachments/assets/ba0593f2-e9f9-48ea-b788-caa559d62fa5)

**Comment by WatchMkr** [comment] 2024-12-06 04:11
Duplicate of https://github.com/pop-os/cosmic-workspaces-epoch/issues/66

**Closed by WatchMkr** 2024-12-06 04:11 UTC
